services:
  - type: worker
    name: coh3stats-worker
    runtime: python
    region: frankfurt  # European region for better latency
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: MONGO_URI
        sync: false  # You'll set this in Render dashboard
      - key: CHECK_INTERVAL
        value: 900  # 15 minutes in seconds
      - key: LOG_LEVEL
        value: INFO  # Default log level
    autoDeploy: true
    healthCheckPath: /healthz 